export const config = {
    barWidth: 49.5,
    repairPower: 0.3,
    currency: 0,
    repairCost: 5,
    workPower: 0.3,
}

export const houseArray = [{
        houseId: "houseOne",
        houseCost: 100,
        purchased: false,
        stageOneHp: 20,
        stageTwoHp: 50,
        stageThreeHp: 100,
        currentHouseHp: 0,
        stageOneValue: 0.3,
        stageTwoValue: 0.7,
        stageThreeValue: 1.5,
        houseBio: "A small cardboard box to protect against the elements",
    },
    {
        houseId: "houseTwo",
        houseCost: 1000,
        purchased: false,
        stageOneHp: 500,
        stageTwoHp: 800,
        stageThreeHp: 1200,
        currentHouseHp: 0,
        stageOneValue: 1.2,
        stageTwoValue: 2.5,
        stageThreeValue: 5,
        houseBio: "A shack, four wooden walls and and a roof. Perfect for hipsters",
    },
];